# App Info
ios_app_id                                : 1460691685                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/studyr/id1460691685                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Studyr                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : ⠀                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The smart student planner you have been waiting for

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : SASystems                                
your_link                                 : http://sasystems.ch                     
your_city                                 : Zurich, Switzerland                                
email_address                             : 
facebook_username                         : studyrapp                                          
instagram_username                        : 
twitter_username                          : studyrtheapp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Planner & Classes
    description                           : Enrollment management with terms and courses. Add classes with custom class types. Support for repetitive and MWF classes
    fontawesome_icon_name                 : university
    
  - title                                 : Calendar
    description                           : Month and week overview. Shows all activities (Classes, Homework, Gradings). Add extra-curricular events
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Class management
    description                           : Skip single classes (attendance tracking) and see overview for each course. Delete single classes when they got canceled
    fontawesome_icon_name                 : chalkboard-teacher

  - title                                 : Homework
    description                           : Add all your homework. Set priority levels, and reminders. Create repeating homework. Filter to show completed ones. Sort by date, course, or priority
    fontawesome_icon_name                 : clipboard-list

  - title                                 : Grading
    description                           : Add all your grading and assignments. Set grades, weigths, and reminders. Customize your grading scales. Create repeating gradings. Sort by date or course.
    fontawesome_icon_name                 : award
    
  - title                                 : Integration
    description                           : Shows events from the system calendar. Calendar sharing to integrate Studyr with Google Calendar, Apple Calendar, or any other 3rd party app which supports iCal
    fontawesome_icon_name                 : handshake


# Theme Settings
topbar_color                              : "#298FFF"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.1

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#298FFF"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#298FFF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
